### ISSUE TITLE
In the demo, the calendar doesn't work until a date is chosen

### ISSUE THREAD

**Issue by fabianmossberg** [6eDesign/svelte-calendar#102]
When I open the demo page and i click on any of the buttons to open the calendar,  the default date is today (December 9).

However, the month that is shown does not seem to be december. Only 29, 30 and 31 are enabled for click, they are all 29, 30 and 31 of October 1987.

Before choosing any of them I can click the "next month" button,  it moves forward one month at a time, but the calendar itself does not move. The "previous month" button does not get enabled.

To activate the calendar I have to pick one of the three available dates in the end of October 1987, after that the calendar starts to work as expected.

![Video of the error](https://user-images.githubusercontent.com/1999142/101554251-8ef23080-39b6-11eb-8172-731ca6ed3b3f.gif)

**Comment by 6eDesign** [comment]
Fixed in version `2.0.x` - start and end date defaults have been updated to 1 year ago and 1 year in future, respectively.
