### ISSUE TITLE
Allow Responsive Design

### ISSUE THREAD

**Issue by zdenda-online** [6eDesign/svelte-calendar#107]
Hello, the component is nice but the fact the button is fixed 300px limits the use for responsive design.
It would be fine to allow styling not only wrapping div but mainly the button. Or at least make button width 100% instead of fixed value and let parent (client) component to decide its width (e.g. by wrapping to div)

It is typical that mobile devices have width of input elements (buttons etc) on 100%.

**Comment by 6eDesign** [comment]
You can supply your own button to the component with whatever styling you'd like.  There are examples of this in the demo but to summarize you just pass your button as a child/slot of the datepicker.

**Comment by zdenda-online** [comment]
Oh I missed that, sorry my apologies.

**Comment by 6eDesign** [comment]
No worries at all.  Thank you
