### ISSUE TITLE
<Popover> received an unexpected slot "default".

### ISSUE THREAD

**Issue by r-franke** [6eDesign/svelte-calendar#108]
All examples given result in the above error message. I checked the slots that are being filled and they all seem to be okay.

Anyone else seeing this?

**Comment by oldtinroof** [comment]
Yep, I'm getting the same thing. I had a look through the source, but am fairly new to svelte so can't see anything obvious.

**Comment by AlexMordred** [comment]
Also getting this.

**Comment by KTruong008** [comment]
I think this issue is fixed if you upgrade svelte to v3.35.0 https://github.com/sveltejs/svelte/issues/4546.

**Comment by AlexMordred** [comment]
@KTruong008 it worked, thanks!
