### ISSUE TITLE
What about internacionalization?

### ISSUE THREAD

**Issue by EriksonGM** [6eDesign/svelte-calendar#110]
Can we change the month to spanish or another lenguage?

Would be nice some internacionalization features.

**Comment by jonathangreenemeier-vizio** [comment]
Please check the readme for instructions

**Comment by AndreasMaros** [comment]
Have you seen https://github.com/6eDesign/svelte-calendar#daysofweek-and-monthsofyear? That should do excatly what you're looking for.

**Comment by 6eDesign** [comment]
The next version of this calendar will require dayjs as a peer dependency.  I believe we will be able to rely on it solely for locales.

**Comment by 6eDesign** [comment]
Localization has been overhauled in the latest release of svelte-calendar (v3.x).  Please check out the [localization example](https://6edesign.github.io/svelte-calendar/docs/examples) on this page.  Feel free to open a new issue with additional feedback/bugs/etc.
