### ISSUE TITLE
Prop to style individual days

### ISSUE THREAD

**Issue by rmcew** [6eDesign/svelte-calendar#111]
Would be nice if we could style individual days on the calendar. I'm thinking a prop similar to selectableCallback, wherein you provide a function that takes a date and returns a CSS class that gets added to the div that wraps each day.

**Comment by 6eDesign** [comment]
I'm not sure this sort of thing would be very widely used.  You could, however, accomplish this using `:nth-child()` within a `:global()` selector in one of the component's parents.  I'm going to close this for now but can re-evaluate if there's additional demand or reasoning for this sort of thing.
