### ISSUE TITLE
Non-reactive monthsOfYear with daysOfWeek

### ISSUE THREAD

**Issue by lexey111** [6eDesign/svelte-calendar#112]
I observe strange behaviour in case `daysOfWeek` and `monthsOfYear` both are dynamic: only `monthsOfYear` reacts on change.

```ts
<Datepicker
   weekStart={app_state.dateLocale === 'en' ? 0 : 1}
   monthsOfYear={Calendar[app_state.dateLocale].monthsOfYear}
   daysOfWeek={Calendar[app_state.dateLocale].daysOfWeek}/>
```

`Calendar` is just a const which contains localised arrays, arrays are correct. The component receives initial locale and updates both months and days (and `weekStart`, btw), but when locale changes - only months update correct, days (and `weekStart`) still use initial values. 

If wrap the component in some dynamic code which will hide it and re-render on locale changes - everything works fine.

**Comment by 6eDesign** [comment]
Localization has been overhauled in the latest release of svelte-calendar (v3.x).  Please check out the [localization example](https://6edesign.github.io/svelte-calendar/docs/examples) on this page.  Localization is still not reactive but I have called this out more clearly in the documentation.  Do you think there's a realistic need to change locales for an already-initialized calendar?
