### ISSUE TITLE
Kit - Error when evaluating SSR module

### ISSUE THREAD

**Issue by riez** [6eDesign/svelte-calendar#113]
Installing on svelte-kit using dev-dependecies got error:
```
[vite] Error when evaluating SSR module /src/components/atoms/FormInput/Datepicker.svelte:
Error: Cannot find module 'svelte-calendar' from '
```

But when installing as dependencies its working but I always need to restart dev server whenever made changes on component props. eg:
```
import Calendar from "svelte-calendar";
<Calendar />
```
change to
```
import Calendar from "svelte-calendar";
<Calendar
  buttonBackgroundColor='#e20074'
  buttonTextColor='white'
  highlightColor='#e20074'
  dayBackgroundColor='#efefef'
  dayTextColor='#333'
  dayHighlightedBackgroundColor='#e20074'
  dayHighlightedTextColor='#fff'
/>
```

I need to restart the dev server for this to taking effect. I'm using:

```
"@sveltejs/adapter-node": "1.0.0-next.9",
"@sveltejs/kit": "1.0.0-next.54",
```

Please give me some insight on what's going on here.

**Comment by 6eDesign** [comment]
I have not tried using svelte-calendar@2.x in svelte-kit but did recently re-write the calendar using svelte-kit for development, documentation, and publishing and released this as [svelte-calendar@v3](https://6edesign.github.io/svelte-calendar/).  

There are several breaking changes in this new version (hopefully all for the better) but please do check it out and let me know if it's working better for you in your svelte-kit application.  

Also, I noticed you're doing quite a bit of custom theming in your example.  This experience has been overhauled considerably in the new v3 version.  You can edit/preview a custom theme here: [theming-editor](https://6edesign.github.io/svelte-calendar/docs/theme-editor/dark)
