### ISSUE TITLE
Dependency error with dayjs when running dev server with SvelteKit 1.0.0-next.168

### ISSUE THREAD

**Issue by nstuyvesant** [6eDesign/svelte-calendar#125]
Just installed svelte-calendar@3.0.5 into my project (previously using 2.0.4).

Even though svelte-calendar has **dayjs** in its package.json as a dependency, got this error until I explicitly added **dayjs** to my devDependencies:

> 1:35:34 PM [vite] Internal server error: Failed to resolve import "dayjs" from "node_modules/svelte-calendar/src/lib/components/Datepicker.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/src/lib/components/Datepicker.svelte
>   41 |  } from "svelte/internal";
>   42 |  
>   43 |  import dayjs from 'dayjs';
>      |                     ^
>   44 |  import datepickerStore from '$lib/stores/datepicker';
>   45 |  import { keyControlsContextKey, storeContextKey } from '$lib/context';
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50142:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50138:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75860:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75995:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50352:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65393:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65521:32)
> 1:35:34 PM [vite] Internal server error: Failed to resolve import "dayjs" from "node_modules/svelte-calendar/src/lib/components/InlineCalendar.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/src/lib/components/InlineCalendar.svelte
>   26 |  } from "svelte/internal";
>   27 |  
>   28 |  import dayjs from 'dayjs';
>      |                     ^
>   29 |  import datepickerStore from '$lib/stores/datepicker';
>   30 |  import { keyControlsContextKey, storeContextKey } from '$lib/context';
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50142:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50138:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75860:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75995:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50352:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65393:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65521:32)
> 1:35:34 PM [vite] Internal server error: Failed to resolve import "dayjs" from "node_modules/svelte-calendar/src/lib/components/Datepicker.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/src/lib/components/Datepicker.svelte
>   41 |  } from "svelte/internal";
>   42 |  
>   43 |  import dayjs from 'dayjs';
>      |                     ^
>   44 |  import datepickerStore from '$lib/stores/datepicker';
>   45 |  import { keyControlsContextKey, storeContextKey } from '$lib/context';
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50142:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50138:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75860:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75995:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50352:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65393:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65521:32)
> 1:35:34 PM [vite] Internal server error: Failed to resolve import "dayjs" from "node_modules/svelte-calendar/src/lib/components/InlineCalendar.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/src/lib/components/InlineCalendar.svelte
>   26 |  } from "svelte/internal";
>   27 |  
>   28 |  import dayjs from 'dayjs';
>      |                     ^
>   29 |  import datepickerStore from '$lib/stores/datepicker';
>   30 |  import { keyControlsContextKey, storeContextKey } from '$lib/context';
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50142:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50138:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75860:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75995:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:50352:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65393:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:65521:32)

To reproduce...
- npm init svelte@next my-app (specify SvelteKit Demo App, TypeScript: yes, eslint: no, prettier: no)
- cd my-app
- npm install svelte-calendar
- edit /src/routes/index.svelte and add  `import Datepicker from 'svelte-calendar';` to the `<script lang="ts">` block and `<Datepicker />` anywhere in the template.
- npm run dev -- --open

**Comment by nstuyvesant** [comment]
Reverting back to svelte-calendar@2.0.4 is my temporary workaround.

**Comment by jonathangreenemeier-vizio** [comment]
Thanks for taking a look at the new v3. It's a complete rewrite and was built with svelte kit as well. I will try to look into this and find a solution.  I think dayjs might need to be a peer dependency to allow for localization

**Comment by nstuyvesant** [comment]
Looks like there's a lot of good stuff in v3 (TypeScript was on my wish list). For the two items I ran into, it might be just a matter of documentation - not sure.

**Comment by nstuyvesant** [comment]
Resolved in 3.0.19
