### ISSUE TITLE
Error when evaluating SSR module when running SvelteKit 1.0.0-next.168 dev server

### ISSUE THREAD

**Issue by nstuyvesant** [6eDesign/svelte-calendar#126]
After explicitly adding **dayjs** to my devDependencies in my package.json per https://github.com/6eDesign/svelte-calendar/issues/125, I get:
> 1:47:35 PM [vite] Error when evaluating SSR module /node_modules/svelte-calendar/src/lib/components/Datepicker.svelte:
> Error: failed to load module for ssr: /src/lib/stores/datepicker
>     at instantiateModule (/Users/nates/dev/my-app/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75058:15)
> 1:47:35 PM [vite] Error when evaluating SSR module /node_modules/svelte-calendar/index.js:
> Error: failed to load module for ssr: /src/lib/stores/datepicker
>     at instantiateModule (/Users/nates/dev/my-app/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75058:15)
> 1:47:35 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
> Error: failed to load module for ssr: /src/lib/stores/datepicker
>     at instantiateModule (/Users/nates/dev/my-app/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75058:15)
> failed to load module for ssr: /src/lib/stores/datepicker
> Error: failed to load module for ssr: /src/lib/stores/datepicker
>     at instantiateModule (/Users/nates/dev/my-app/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:75058:15)

when doing an `npm run dev -- --open` with a fresh SvelteKit project that imports Datepicker and uses the component on /src/routes/index.svelte.

**Comment by nstuyvesant** [comment]
Reverting back to svelte-calendar@2.0.4 is my temporary workaround.

**Comment by jzillmann** [comment]
Same problem here with Svelte kit.
Didn't include `dayjs`.
Using `svelte-calendar@2.0.4` works.
Also having errors in VSCode (my project is a typescript one)
- with `2.0.4`: `SX element type 'Datepicker' does not have any construct or call signatures.`
- with `3.x`: `Type '{}' is not assignable to type 'IntrinsicAttributes & { formatted: string; selected?: Date; start?: Date; end?: Date; theme?: {}; defaultTheme?: any; format?: string; store?: { set: (this: void, value: { open: boolean; ... 8 more ...; activeViewDirection: number; }) => void; ... 11 more ...; getCalendarPage(month: any, year: any): { ...; }[]; }; }'.
  Property 'formatted' is missing in type '{}' but required in type '{ formatted: string; selected?: Date; start?: Date; end?: Date; theme?: {}; defaultTheme?: any; format?: string; store?: { set: (this: void, value: { open: boolean; hasChosen: boolean; selected: any; start: Date; ... 5 more ...; activeViewDirection: number; }) => void; ... 11 more ...; getCalendarPage(month: any, ye...'`

Wonderful calendar by the way!

**Comment by 6eDesign** [comment]
Packaging configuration updates have been applied and sveltekit-specific instructions have been added to the README.  Please re-open/comment if you are continuing to have issues after updating svelte-calendar and updating your `svelte.config.js`.
