### ISSUE TITLE
Strange positioning when in mobile layout

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#13]
Not sure why, but the calendar appears disconnected from the trigger button when on a mobile view.

This may or may not be related to use of a modal, but is very strange.

![screenshot from 2019-02-18 17-46-47](https://user-images.githubusercontent.com/218949/52968498-44e52880-33a5-11e9-9fe9-92a0c644f2d8.png)

**Comment by antony** [comment]
Live example: https://github.com/beyonk-adventures/svelte-calendar/tree/feature/positioning-fix

**Comment by antony** [comment]
Ah I know why this is - the Calendar attaches to bottom in < 480px.

Think this is fine, but it's a different issue - the calendar needs to be drawn outside of the bounds of a modal, especially at this screen width.

**Comment by 6eDesign** [comment]
Yeah we wanted it to be close to your thumb when on a mobile device (similar to native select inputs on Android/iOS).  Can you set overflow:visible on your modal?

**Comment by antony** [comment]
@6eDesign haha - just reached this conclusion after a couple of hours hacking.

`overflow: auto` on the container is what breaks the calendar - across any device. even if there is enough room, the calendar pops up halfway hidden and too far left.

The fix is `overflow: visible` as you suggest. Should this be in the docs perhaps?

**Comment by 6eDesign** [comment]
Not a bad idea, I ran into this as well on one of our pages.  I'm not sure if that solution will work for everyone, though. 

Do you like the placement on mobile?  I could probably make this optional if not.

**Comment by antony** [comment]
@6eDesign placement on mobile is excellent - I think documenting `overflow: visible` is a good pointer, even if it's not a be-all-end-all-solution, since my initial thoughts were that I would need to detach the popup from the dom and re-attach it at a node further up the tree.
