### ISSUE TITLE
Enlarge mode is broken with a small width

### ISSUE THREAD

**Issue by Ortyommm** [6eDesign/svelte-calendar#132]
![image](https://user-images.githubusercontent.com/78483221/134195038-8b91c7cd-267a-40af-817b-50fcd829faee.png)
![image](https://user-images.githubusercontent.com/78483221/134195560-8cff4522-5bc0-472a-8b85-f3beaefb0d90.png)
First example is from playground, second is from my project(width:500).

**Comment by 6eDesign** [comment]
You can modify the size of the enlarged text in the theme-editor (`calendar.font.large`).  Does that resolve your issue?

**Comment by Ortyommm** [comment]
Yes, it looks much better, thank you a lot!
![image](https://user-images.githubusercontent.com/78483221/134280833-e893a3e2-17ae-428f-9139-238e587787ff.png)
