### ISSUE TITLE
Calendar not working in firefox

### ISSUE THREAD

**Issue by richardatianperks** [6eDesign/svelte-calendar#135]
When viewing the date picker in a firefox browser, the day part of the calendar control doesn't render, only the year and month are visisble.

![image](https://user-images.githubusercontent.com/19780873/136525603-f4dedb8b-6f8a-4ae8-a96a-768c78c48baf.png)

**Comment by 6eDesign** [comment]
Can you please provide more info to reproduce the issue?  (Browser version, OS, and the code you're using).  This isn't something I'm seeing in firefox
