### ISSUE TITLE
Some extra props

### ISSUE THREAD

**Issue by multipliedtwice** [6eDesign/svelte-calendar#138]
Hello, thank you for the awesome library. Do you have any plans to add any of the following:
1. startAt - for example to open the calendar on 18 years ago date?
3. allow to input use Unix timestamp as a selectedDate?

**Comment by jonathangreenemeier-vizio** [comment]
For #1, this is possible by setting or binding the `selectedProp` to a specific date: https://svelte.dev/repl/0c1cbd9bb5ee4be2a65fd843d2427c6b?version=3.44.1

You may have to adjust the `start` and `end` properties (date boundaries) if the start date it outside of the defaults.  See the [props documentation](https://6edesign.github.io/svelte-calendar/docs/props) for more details.  

I'm not quite sure what you mean by #2.

**Comment by multipliedtwice** [comment]
Thank you.
