### ISSUE TITLE
When store variable named anything but 'store' the Custom Trigger wont update with the date.

### ISSUE THREAD

**Issue by Edward-Ta** [6eDesign/svelte-calendar#146]
https://svelte.dev/repl/2088b86f95ed4e83af1b698c7e76d3f3?version=3.44.2

Title says it all.

**Comment by taffit** [comment]
Not an issue.    
Please note, that you can only use the shorthand, if the [property matches the variable](https://svelte.dev/docs#template-syntax-element-directives-bind-property).

See https://svelte.dev/repl/b7f0570976ff408faee92c504533f708?version=3.44.2

**Comment by Edward-Ta** [comment]
Thank you it works perfectly now, you have resolved my misunderstanding.
