### ISSUE TITLE
Refuses to change month when wrapped in a label

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#17]
Not sure I understand exactly what's going on here, but I have a library called `components`, and I use datepicker within it.

I then import that project into my Sapper project.

At this point, it's impossible to change the month on the picker - it simply animates and ends up back on the same month.

I'll try and re-create this but getting in here early in case you have any immediate thoughts!

**Comment by 6eDesign** [comment]
Is the components library something I can access in order to reproduce the issue on my machine?

**Comment by antony** [comment]
Trying to recreate this issue, and ran into an even weirder issue, simply trying to get the component to render - I think something odd is going on with component properties...

I had to dive into node_modules and replace all instances of the word `start`with `starty` otherwise it wouldn't ever set the value (even from `data()`) and the component wouldn't render.

Now I've done that it renders fine but I can't recreate the original issue, yet.

**Comment by antony** [comment]
Okay, I feel like this `start` thong is a total misonomer for now, so I'm going to ignore it.

I think I've nailed down the problem, but I'm not sure why this occurs with the wrapped version of the library and not the native.

It looks like clicking anything on the NavBar component triggers the open() method again, so my component (Whilst looking static) just opens over and over again at the current date.

![Screenshot from 2019-04-01 12-36-19](https://user-images.githubusercontent.com/218949/55324822-22056400-547b-11e9-8a86-28f12313707d.png)

Any ideas what might cause this?

**Comment by antony** [comment]
This fixes it:

```
      registerOpen() {
        let { selected, open } = this.get();
        if (open) { return }
        ...
      },
      registerClose() {
        this.set({ open: false });
        ...
      }
```

but it feels like a hack.

**Comment by antony** [comment]
Ah - managed to recreate it for you!

https://github.com/beyonk-adventures/calendar-bug-demo

**Comment by antony** [comment]
It's the label. Wrapping the whole thing in label is the thing which breaks it. Phew!

Okay so - I've been told over a period of many years that wrapping form controls in labels is the way to it (even by Rich when I mentioned that using an id isn't really a good idea in Svelte).

What's your opinion.

Is this a misuse of label in this instance? Is it a bug with the library? Or something else...

**Comment by 6eDesign** [comment]
Hmm, ok that seems like something we could fix easily enough.  In the meantime you could probably put the label inside of the calendar component (in place of or wrapping the button).  I'll try to look at fixing this tonight or later this week though.

**Comment by antony** [comment]
@6eDesign awesome - if you think it's a fixable issue that would be ideal.

Right now I've replaced the label with a thing which looks like a label, which works too.
