### ISSUE TITLE
Pick dates in UTC

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#18]
Since the UK ticked over from GMT to BST, the datepicker is now picking dates in BST, which on the surface, is fine.

However, if I then take those dates and turn them to UTC to store them, my "start of day" time becomes 11pm yesterday.

A bit confusing this one, but essentially I want to say that picking 1st of May 2019 is 1st of May 2019, and not 30th April 2019. I don't have any control over this with the current component.

Any ideas for how we can improve this?

**Comment by 6eDesign** [comment]
I believe the date picker would be generating dates in the client's timezone.  If you convert this date to a different timezone/format then I _think_ it would be expected that the time (and sometimes the date/day) would be different as well.  Converting it back into the client's timezone should yield the same date/time.  

You could pull day, month, and year from the date object and use that to store the date in a format that is not timezone-specific, but I'm not sure that would suit everyone's needs.

**Comment by 6eDesign** [comment]
Hey @antony - I'd like to resolve this for you, somehow.. maybe I could make the date attributes bindable?  Such that you could say something like `<Datepicker bind:month bind:year bind:day />` and then you can assemble a date object using those integers regardless of timezone?

**Comment by antony** [comment]
Hey @6eDesign - Thanks for thinking about this! I don't know if this is strictly necessary since for dd/mm/yyyy it's easy enough to pull the values off the `Date` object returned by the picker.

For now I think it may be best to leave it as is.
