### ISSUE TITLE
formattedSelected is not updated if the current date is selected

### ISSUE THREAD

**Issue by Mattinn** [6eDesign/svelte-calendar#19]
Hi I noticed this strange behavior, am I doing something wrong or is it a bug ? 

```html
      <DatePicker format='{dateFormat}' 
                  bind:selected=startDate 
                  bind:dateChosen=startDateChosen 
                  bind:formattedSelected=startDateFormatted>
            <button class='dateBtn'>
                  {#if startDateChosen} {startDateFormatted} {:else} {$_('selectDate')} {/if}
           </button>
      </DatePicker>
```
```javascript
    data() {
      return {
        dateFormat: "#{j}. #{n}. #{Y}", 
        startDate: new Date(),
        startDateChosen: false,
        startDateFormatted: 'Format me!',
    }
```

![formattedSelected ](https://user-images.githubusercontent.com/2447396/58808355-892dc900-8622-11e9-973f-a8724932c329.gif)

**Comment by 6eDesign** [comment]
Hello @mattinn, I think you're missing some parentheses next to `new Date` in your data function.  Please try ```data() {
      return {
        dateFormat: "#{j}. #{n}. #{Y}", 
        startDate: new Date(),
        startDateChosen: false,
        startDateFormatted: 'Format me!',
    }``` 
And please let me know if this doesn't resolve the issue.

**Comment by Mattinn** [comment]
Ah silly me but it did not resolve the error

**Comment by Mattinn** [comment]
The problem is that the computed `formattedSelected` listens to `selected` and  `format ` 
The format is a default value in my code and the date I selected is the same as the Datepickers default value - so there is no change to trigger `formattedSelected` 

Now that i set the format in oncreate function instead of having it a default value, it works - could you force the computed to run every time?

**Comment by Mattinn** [comment]
Perhaps it would work to just add `dateChosen` as one of the dependencies for `formattedSelected` ?

**Comment by 6eDesign** [comment]
@Mattinn - I have been able to reproduce the issue.  I have not been using this component in the way you've described above.  Thanks for bringing this to my attention!  

A simple interim/quick-fix would be for you to set `startDateFormatted` to `undefined` in your data function.  Please let me know if this does not fix this for you in the meantime.  I'll work on a more permanent fix.

**Comment by Mattinn** [comment]
Yes that solved my issue thanks, good work on this component btw :)
