### ISSUE TITLE
Update for Svelte 3

### ISSUE THREAD

**Issue by Vehmloewff** [6eDesign/svelte-calendar#20]
This is a very useful date picker.

It would be nice if it were compatible with Svelte 3.

**Comment by 6eDesign** [comment]
@Vehmloewff Thank you!  I'll need to find a little time to convert this over to v3 but this is on my radar.  I'll keep this issue to track progress and let you know when it's ready in v3.

**Comment by Vehmloewff** [comment]
I might be worthwhile to wait for [svelte-upgrade](https://github.com/sveltejs/svelte-upgrade/tree/v3) to get a bit better.

**Comment by antony** [comment]
@6eDesign I'm going to take a crack at upgrading. I don't know how successful I'll be!

**Comment by antony** [comment]
:+1:
