### ISSUE TITLE
Arbitrary setting of end date to 29th Oct 2020.

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#21]
Is there a reason for the assigning of an end date for the calendar?

I've been implementing this in my app and not bothering to set an end date since I don't have a restriction. However the library forces me to pick one, so I'd have to set something like 2030.

I'm wondering if it would be a good idea to have null as the default for end date, so that people can pick any date they want.

Thoughts?

**Comment by 6eDesign** [comment]
Currently the calendar generates all of the months when instantiated so it would not be possible to have it completely unrestricted/null.  This is not a technical limitation, though, and we could certainly generate the required months on-the-fly if we really wanted to support infinite date ranges. 

Perhaps in the meantime we should increase the default end date, though.

**Comment by antony** [comment]
I think the quickest solution is to document the end date. I'll add some docs now. We can't usefully guess a user's required end date, so should probably just roadmap on-the-fly generation, and let users choose it themselves.
