### ISSUE TITLE
Allow calendar wrapper to extend outside its container.

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#22]
The calendar is tricky to use in a modal right now because it won't use the full screen real estate if it is contained within an element.

You can see what I mean here.

![popover](https://user-images.githubusercontent.com/218949/59561889-45bd5c80-901d-11e9-946c-3360ba306e7b.png)

The way I've seen other calendars solve this is to have an optional "detached" mode where the calendar element re-parents itself to the div specified in the option.

Not sure if you have a better idea of how to solve this?

**Comment by antony** [comment]
Btw `position: fixed` in dev-tools immediately fixes this. Is that an oversimplification?

**Comment by 6eDesign** [comment]
Hey @antony  - I have been able to workaround this type of thing with `overflow: visible` on the parent.  I think this is probably the cleanest solution but if it doesn't work for you it might be helpful to see a reproduction of your specific issue (with whichever CSS you're using for your modal).

**Comment by antony** [comment]
In the end I replaced my modal - but I needed to keep overflow: scroll on the parent as it is a modal and sometimes the content won't fit on the screen.

**Comment by antony** [comment]
I can see the issue with this now. On a large screen the datepicker sits right in the middle with:

`position: fixed`

The way to fix it is to remove top and left from `.contents-wrapper`. Not sure what other issues this might cause though.

**Comment by benquan** [comment]
I have the same issue. the component sits on a sidebar which has overflow set to scroll (there is a long list). so you cant see the whole calendar.
