### ISSUE TITLE
Add github tags

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#25]
People find svelte-components hard to find still, I think adding some tags on the github repo would make this easier to find for people.

**Comment by 6eDesign** [comment]
@antony - how exactly do you add github tags?

**Comment by antony** [comment]
Just click "Manage Topics" under "Description"

**Comment by 6eDesign** [comment]
Thanks @antony  - I've added a few tags of the svelte and 'calendar' varieties.
