### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#26]
I ran the project through airbnb's eslint as I assumed that's kinda what people who don't use `standard` like I do use. There are about 20,000 fixable errors, and 650 warnings

Do you have a code-style preference? Happy to set up some linting if you have a style in mind.

**Comment by 6eDesign** [comment]
I'm fine with Airbnb assuming there's good editor support.  Happy to take a look at this setup if you could submit a PR, perhaps we do this after merging the svelte 3 update.

**Comment by 6eDesign** [comment]
I have added eslint with the Airbnb configuration.  I've included this in the test script so that it is run as part of the release process.
