### ISSUE TITLE
Use stores for all data

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#27]
There is quite a bit of prop passing going on inside the library, and I think with Svelte 3 we are well positioned to move all that data into a store.

**Comment by 6eDesign** [comment]
I agree this would be beneficial and plan to work on this when I have a little free time.  Thanks for the suggestion.

**Comment by antony** [comment]
Upgrading this to suggest we actually use Stores within the Context API.

Each calendar instance should expose a context and that can be used to share data between days/months/years.
