### ISSUE TITLE
Plugin doesn't work with Sapper

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#28]
Though the built-in demo works, the plugin doesn't work with Sapper any more, since it has a problem with the way timeUtils exports for the browser.

The exact issue is:

```
✗ client
node_modules/svelte-calendar/src/Components/Datepicker.svelte (8:9)
'formatDate' is not exported by node_modules/timeUtils/dist/timeUtils.umd.js
 6:     {trigger}
 7:     on:opened={registerOpen}
 8:     on:closed={registerClose}
             ^
 9:   >
10:     <div slot="trigger">
```

I'm not proficient enough in rollup/isomorphic modules to understand this, wondering if maybe you could shed some light?

**Comment by 6eDesign** [comment]
Hey @antony - I have not worked much with Sapper yet.  Any chance you could point me in the right direction for reproducing this locally?  TimeUtils does export CJS, ESM, and UMD bundles (https://github.com/6eDesign/timeUtils/blob/master/package.json#L5-L7), so I imagine this is fixable.   

When you say it doesn't work in Sapper "any more", does that mean it _was_ working with Svelte V2 in Sapper?

**Comment by ryanatkn** [comment]
The same error happens with [sveltejs/template](https://github.com/sveltejs/template) - here are the steps to reproduce, and [here's a repo that reproduces](https://github.com/ryanatkn/svelte-calendar-bug/).

```bash
npx degit sveltejs/template svelte-calendar-bug
cd svelte-calendar-bug
npm i
npm run dev # works at this point
npm i -D svelte-calendar
```

change `src/App.svelte` to:

```html
<script>
  import Calendar from "svelte-calendar";
  export let name;
</script>
```

```bash
npm run dev

# rollup v1.16.7
# bundles src/main.js → public/bundle.js...
# [!] Error: 'formatDate' is not exported by node_modules/timeUtils/dist/timeUtils.umd.js
# https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
# node_modules/svelte-calendar/src/Components/Datepicker.svelte (34:9)
# 32:           {#each dayDict as day}
# 33:             <span>{day.abbrev}</span>
# 34:           {/each}
#              ^
# 35:         </div>
# 36:         <Month 
# Error: 'formatDate' is not exported by node_modules/timeUtils/dist/timeUtils.umd.js
#     at error (node_modules/rollup/dist/rollup.js:9402:30)
#     at Module.error (node_modules/rollup/dist/rollup.js:13341:9)
#     at handleMissingExport (node_modules/rollup/dist/rollup.js:13263:21)
#     at Module.traceVariable (node_modules/rollup/dist/rollup.js:13650:17)
#     at ModuleScope.findVariable (node_modules/rollup/dist/rollup.js:12361:39)
#     at FunctionScope.findVariable (node_modules/rollup/dist/rollup.js:2964:38)
#     at ChildScope.findVariable (node_modules/rollup/dist/rollup.js:2964:38)
#     at ReturnValueScope.findVariable (node_modules/rollup/dist/rollup.js:2964:38)
#     at ChildScope.findVariable (node_modules/rollup/dist/rollup.js:2964:38)
#     at BlockScope.findVariable (node_modules/rollup/dist/rollup.js:2964:38)
```

**Comment by antony** [comment]
@6eDesign I was using webpack with v2 so it's hard to say. Rollup doesn't tolerate dynamic imports, but I don't think timeUtils uses those?

The rollup-plugin-resolve module for client uses `browser: true` (as I'm sure the svelte template above does), and that causes it to use the umd build in clientside environments. It's something about the way that build works that is causing the issue.

**Comment by 6eDesign** [comment]
Thanks for the responses.  I used @ryanatkn reproduction steps and it looks like things are fixed on svelte-calendar@1.0.3.  @antony let me know if this change does not also fix your issue.

**Comment by antony** [comment]
All good from here! Thanks!

**Comment by artur-sim** [comment]
Im importing like this  import Datepicker from "../../node_modules/svelte-calendar"

**Comment by antony** [comment]
@artur-sim not sure what your comment relates to, but this issue is closed.

Regardless, you should import the datepicker like this:

`import Datepicker from 'svelte-calendar'`
