### ISSUE TITLE
Needs sticky position

### ISSUE THREAD

**Issue by Crisfole** [6eDesign/svelte-calendar#30]
When located near the bottom or top of the page (as in: when on a control panel, or other common location), it gets cut off ☹️ .  Demo:

<img width="388" alt="Screen Shot 2019-07-29 at 9 22 26 PM" src="https://user-images.githubusercontent.com/413237/62093412-313cc880-b247-11e9-871e-b13c06199b19.png">

Otherwise this is awesome! If I fix I'll send a PR...

**Comment by 6eDesign** [comment]
Hi @crisfole, sorry, this was broken when we updated to v3 of svelte.  I'll try to fix ASAP.  In the meantime the previous version is available without this bug.

**Comment by Crisfole** [comment]
No apology owed! This component is awesome. Keep up the good work.

**Comment by 6eDesign** [comment]
Hey @Crisfole  -  this is fixed now (v1.0.4).  Thanks for submitting this issue!
