### ISSUE TITLE
svelte-JSONTable please.

### ISSUE THREAD

**Issue by SenerDemiral** [6eDesign/svelte-calendar#35]

**Comment by SenerDemiral** [comment]
You are amazing. Thank you.
It would be great if you had a chance to add a filter.

**Comment by 6eDesign** [comment]
@SenerDemiral - Just closing this as it's unrelated to svelte-calendar.  If I find the need/motivation, I'll make svelte-table a reality in the future and ping you about it.  If you want to run with the example I posted you're more than welcome, adding filtering should be really easy with svelte.

**Comment by SenerDemiral** [comment]
Thank you for your kindness.
