### ISSUE TITLE
cant figureot how to install o my existing project

### ISSUE THREAD

**Issue by jdgaravito** [6eDesign/svelte-calendar#36]
please upload to npm or yarn please, I want to be able to use it, like the other svelte components in node_modules folder. docs are confusing. said install dependencies  but which ones?

**Comment by 6eDesign** [comment]
@jdgaravito - sorry for any confusion you may be facing.  This is published to NPM already, see here: https://www.npmjs.com/package/svelte-calendar

You just need to run ```npm i --save-dev svelte-calendar``` to use this as an NPM module.  Then, in your application: ```import DatePicker from 'svelte-calendar';'```

Feel free to let me know if you run into any difficulties.  Thank you, I'll try to add these to the docs (which admittedly are not in the best shape).

**Comment by jdgaravito** [comment]
thank you so much for your kind and quick response. One last question, Is there a way to change language? or override the day and months names to a custom ones?
