### ISSUE TITLE
multiple calendars and variables

### ISSUE THREAD

**Issue by jdgaravito** [6eDesign/svelte-calendar#38]
hi its me again, 😄  sorry to bother you.  
i'm trying to have two calendars linked together to pick a start and end dates of an event.
my idea is to update the end date calendar to let users select the date starting from the start date chosen in the previous calendar.

![image](https://user-images.githubusercontent.com/25352320/65365022-95429400-dbdb-11e9-9dfa-c45cc5f0d632.png)

but unfortunately the custom button doesn't update or work with other variables names than `formattedSelected` and `dateChosen`. none of the buttons works even when i declared the variables before. what i'm doing wrong?

and how to display the current local date by default like the uncustomized calendar you have by default.

````
let dateFormat = "#{l} #{j} de #{F} de #{Y}";
let startDateChosen;
let endDateChosen
let formattedSelected;
let endFormattedSelected
// calendar 1
<DatePicker
                format={dateFormat}
                bind:formattedSelected
                bind:startDateChosen>
                <button class="custom-button">
                  {#if startDateChosen}
                    Fecha: {formattedSelected}
                  {:else}Escoge una fecha{/if}
                </button>
</DatePicker>

//calendar 2
<DatePicker
                format={dateFormat}
                bind:endFormattedSelected
                bind:endDateChosen>
                <button class="custom-button">
                  {#if endDateChosen}
                    Fecha: {endFormattedSelected}
                  {:else}{formattedSelected}{/if}
                </button>
</DatePicker>
````   
another small bug i found:  if the calendar is inside a form element, when you have a input field filled with text, after you pick a date, all the form resets to empty again. if a make  the same form with no `<form>` tag it works fine.

thank you so much. i appreciate any help 😃

**Comment by 6eDesign** [comment]
Hey @jdgaravito - the syntax for `bind:property` in svelte looks like this: 
```
bind:EXPORTED_PROPERTY_NAME={LOCAL_VARIABLE_NAME}
```
When you only write the lefthand side of this assignment such as `bind:formattedSelected`, it is equivalent to writing `bind:formattedSelected={formattedSelected}` (it is a shorthand for this common use case).  

`formattedSelected` and `dateChosen` are exported properties ("props").    So if you want to assign one of them to `endFormattedSelected` or `endDateChosen`, you'll have to do so like this: 
```
bind:formattedSelected={endFormattedSelected}
bind:dateChosen={endDateChosen}
```
Here are the docs for this on the svelte website: https://svelte.dev/docs#bind_component_property

Let me know if this doesn't help.  I'm happy to look at the form issue you're describing if it's still a problem.  Could you potentially put together an example of this behavior on the [svelte REPL](https://svelte.dev/repl/hello-world?version=3.12.1)?

**Comment by jdgaravito** [comment]
Jonathan thank you so much. I really appreciate the time you took to help me. I'm starting on web dev and svelte is my first front end framework. Sometimes I felt so overwhelmed and I tried to find component libraries to help me on the process. Unfortunately, due of novelty of Svelte there are not much libraries available and, in the ones that I can find ([](https://madewithsvelte.com/)), their creators never answer the issues posted.  I will try to make it work and i let you know the result. 

about the error, i can't reproduce it, sometimes is the calendar won't appearing or the fields resetting. I think is something related to the live reload and reactivity or the HTTP form defaults.  i will keep on the eye and i will tell u.

**Comment by 6eDesign** [comment]
Thank you for the suggestion @jdgaravito - I had not seen the customization/theming via CSS variables yet.  I'll give this a shot when I have some time.
