### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by antony** [6eDesign/svelte-calendar#4]
- [ ] Run tests
- [ ] Lint
- [ ] Autopublish to npm on tag
- [ ] Badges

**Comment by antony** [comment]
@6eDesign does the travis integration work? is it set up?

**Comment by 6eDesign** [comment]
Not quite - it needs some configuring and some tests need authoring.  I was originally planning on using a similar setup as my timeUtils project but am open to suggestions.  I think we ought to add documentation generation/publishing to the Todo list above.

**Comment by 6eDesign** [comment]
Small update: added the NPM token for Travis.  Tagged commits will now get auto-published.  This can be automated through `npm run release`.   More work to be done here, though - still happy to take a look at the Circle CI config you mentioned in PM.

**Comment by antony** [comment]
@6eDesign I'm going to close this and pop it on a branch and open a new PR. I accidentally did it on master which prevents me opening new PRs :)
