### ISSUE TITLE
Button class "popover" conflicts with Bootstrap's .popover CSS

### ISSUE THREAD

**Issue by pzmarzly** [6eDesign/svelte-calendar#41]
I'm trying to move existing app to Svelte, part by part. I had 2 weird issues with svelte-calendar:

1. borders around buttons were distorted (it didn't cover right side of them)
2. `z-index` of buttons was 1060

It turns out that the class `.popover` is also used in Bootstrap 4.

As a workaround, I can either use a custom version of Bootstrap (as I don't use popovers), or add:

    :global(.datepicker button) { width: initial !important; } /* for the first issue */
    :global(.datepicker .popover) { z-index: unset; } /* for the second */

But a proper fix would be nice (just rename `.popover` to something else).

**Comment by 6eDesign** [comment]
Hey @pzmarzly - thanks for letting me know about this!  I've updated the `.popover` class to `.sc-popover` and will consider adding a namespace to all classes used by this component in the future.  This should publish to NPM momentarily as v1.0.9.  Please let me know if you continue to have any issues.
