### ISSUE TITLE
Browse by year

### ISSUE THREAD

**Issue by perifer** [6eDesign/svelte-calendar#46]
Here is a suggestion: When in "month mode" the previous and next arrows should change a whole year instead of going to previous/next month.

**Comment by skinnedpanda** [comment]
I would include groups of years too, like this https://fengyuanchen.github.io/datepicker/

**Comment by 6eDesign** [comment]
This is a good idea and one that I'd like to implement when I have some free time.  I've labeled this issue accordingly.

**Comment by bato3** [comment]
??duplicate: https://github.com/6eDesign/svelte-calendar/issues/62

**Comment by northkode** [comment]
i have a version of this locally that I built... i can submit it if anyone wants it.

![image](https://user-images.githubusercontent.com/6988083/74547299-2149b500-4f09-11ea-8ac0-b28bd7ba711b.png)

**Comment by antony** [comment]
@northkode would love to see a PR for this!

**Comment by northkode** [comment]
@antony  https://github.com/6eDesign/svelte-calendar/pull/68#issue-375506867

**Comment by 6eDesign** [comment]
A year picking interface has been added in v3 - please refer to the new docs https://6edesign.github.io/svelte-calendar/

It has touch, scroll and keyboard support with new animations
