### ISSUE TITLE
White button text makes calendar useless

### ISSUE THREAD

**Issue by Crisfole** [6eDesign/svelte-calendar#48]
I've got white on blue as my default button, but that means that every button in svelte-calendar is coming out white-on-white, and just a _tad_ hard to use ;).

Any chance you can explicitly set the font color to `inherit` or `black` or `purple` or `cornflower` (I don't particularly care as long as it still looks nice)? Better, can you set it up with css variables for easy overriding?

**Comment by 6eDesign** [comment]
Hi @Crisfole - I'd like to take the CSS variable approach to theming.  This is on my radar and I'll try to make it happen somewhat soon.

**Comment by Crisfole** [comment]
Just for reference, the `var` method accepts variable names _and_ a default. So you can do something like this:

```html
<style>
  .day--label { 
    color: var(--week-button-text-color, inherit);
    display: flex;
    justify-content: center;
    // ...
  }
</style>
```

See here: https://github.com/rob-balfre/svelte-select/blob/9ec6433090c881426a907d68d4b9c3b8bc348c53/src/Select.svelte#L626 for where I stole the technique from.

**Comment by Crisfole** [comment]
@6eDesign I need the color fix ASAP, so I'm going to push a PR in the next few minutes here ;)

**Comment by 6eDesign** [comment]
@Crisfole I pushed a change that allows you to theme the calendar.  I am re-thinking the prop syntax though.  I think I will go with a `styles` prop as an object with various properties instead of multiple style props.   In any case, it likely fixes your issue anyway since it sets an explicit color to the day label button.
