### ISSUE TITLE
Cannot set blank initial selected date

### ISSUE THREAD

**Issue by Eradash** [6eDesign/svelte-calendar#51]
I want to create a DatePicker with no initial selected date.
Currently, the initial value is set at the current date, and I need to be able to have a blank field (forcing the user to set a value before sending the form)

**Comment by 6eDesign** [comment]
@Eradash If I'm understanding you correctly I think you can accomplish this by observing both the selected date (`formattedSelected`/`selected`) and the boolean `dateChosen` (which represents whether the user has chosen a date).  Here is an example: https://svelte.dev/repl/7f20eda431574dbaa825378399240b0a?version=3.12.1

Let me know if this doesn't address the issue you're having.

**Comment by 6eDesign** [comment]
Hey @Eradash - I haven't heard from you in a while so I'm going to close this for now but feel free to re-open if my previous response doesn't address your need or you have other questions.
