### ISSUE TITLE
Re-render selectable days

### ISSUE THREAD

**Issue by jonadeline** [6eDesign/svelte-calendar#56]
Is it possible at the moment to re-render the selectable days after the initial display ?
For exemple I'd like to amend the selectable days according to a city selected from a dropdown list. 
From what I see the `selectbaleCallback` can only be run once at the initialisation ? 

Thank you.

**Comment by 6eDesign** [comment]
This should be possible with some minor changes.  I've labeled this issue as an enhancement and will prioritize accordingly.   Happy to accept a PR as well if you're up to it.

**Comment by antony** [comment]
This can be closed as per https://github.com/6eDesign/svelte-calendar/pull/61
