### ISSUE TITLE
Bug: Changing weekStart leaves out 1st of the month if 1st is on sundays

### ISSUE THREAD

**Issue by Grotlo** [6eDesign/svelte-calendar#57]
With #53 you could change which day started the week, which I needed to be mondays.

However, when I ~~changed the `export let weekStart = 0;` to `1` in `Datepicker.svelte`~~ put `weekStart={1}` in my test file, this happened:

![bilde](https://user-images.githubusercontent.com/36000231/70711374-b221cb80-1ce1-11ea-9e75-e1ff58257d9d.png)

So this means that the 1st of the month is missing if the 1st is on sundays. I.E December 2019, March 2020.

I made it work when I changed this in `lib/helpers.js`

```
const getCalendarPage = (month, year, dayProps, weekStart = 1) => {
    let date = new Date(year, month, 0);
```

This is obviously not a dynamic fix, so I'm hoping someone with more experience than me can make it so. 😇 

~~Also, it seems like `weekStart` doesn't work as intended when going beyond mondays. I don't really see the scenario where one would want the week to start on any other days than sundays or mondays, but with this variable, it seems like we have that option if we want it, when it really just breaks. What it does when going above 1 is just pushing one date to the left until it crashes when going above 6 (which makes sense ofc). So either fixing it so that you could choose any day of the week to start the week or only making it so that you can pick from sundays or mondays is what makes the most sense to me. With something like `let startWeekOnSun = false/true` maybe?~~

EDIT: I've read #37, so I see that the above paragraph has already been discussed.

**Comment by 6eDesign** [comment]
Hey @Grotlo - thanks for reporting this.  I will take a look ASAP and attempt to fix.  I didn't document this feature yet in case it wasn't quite ready for prime time (I didn't work on it myself).

**Comment by 6eDesign** [comment]
`startOfWeekIndex` property has been added in `v3` and seems to be working correctly.
