### ISSUE TITLE
Allow easy selection for year component

### ISSUE THREAD

**Issue by axiopisty** [6eDesign/svelte-calendar#62]
How can you quickly change the year component of the date being selected? I'm experimenting with this component in the context of using it to pick birth dates. I don't see an easy way to pick a date that is many years in the past without having to click on the back button for each month.

**Comment by artur-sim** [comment]
Looking for the same !

**Comment by 6eDesign** [comment]
I've been working on this and hope to have an example ready to share in the near future.

**Comment by northkode** [comment]
![image](https://user-images.githubusercontent.com/6988083/74547368-3f171a00-4f09-11ea-9ae7-6f070c2739c2.png)

I will create a fork of my version if anyone wants it

**Comment by 6eDesign** [comment]
Hey @northkode - happy to look at a PR if you'd like to submit one.

**Comment by northkode** [comment]
@6eDesign  i submitted one issue-62

**Comment by helrabelo** [comment]
any updates?

**Comment by 6eDesign** [comment]
A year picker interface will be included in the next version of the calendar.  It's a bit different than the above implementation but it works well.

**Comment by 6eDesign** [comment]
This has been added in the v3.x release.  You can check it out here https://6edesign.github.io/svelte-calendar/

The whole UI has been overhauled with new animations and UX.  You can scroll, drag, or control the day, month, and year pickers with the keyboard.
