### ISSUE TITLE
Bug: calendar lingers when navigating to a different page

### ISSUE THREAD

**Issue by Grotlo** [6eDesign/svelte-calendar#65]
When you navigate out of a page which has the calendar, the previous page lingers between a quarter and a half second before destroying. I found that the issue lies with line 18 in `Week.svelte`:

`out:fade={{ duration: 180 }}`

```
<div 
  class="week" 
  in:fly={{ x: direction * 50, duration: 180, delay: 90 }}
  out:fade={{ duration: 180 }}
>
```

I haven't made a PR on this since I couldn't figure out how to replace that line in CSS.

**Comment by antony** [comment]
I think this relates to the way transitions work in Svelte/Sapper. I'm experiencing an issue now where the calendar's use of transitions actually breaks Sapper's routing.

**Comment by antony** [comment]
Relates to this issue: https://github.com/sveltejs/sapper/issues/814
