### ISSUE TITLE
Very slick Calendar but how:  "Can be compiled to a native web component / custom element"

### ISSUE THREAD

**Issue by tonysoft** [6eDesign/svelte-calendar#66]
I have brought the component and sub-components into a stock svelte dev env, get everything to build, but can't see any visual when using the custom element tag I choose.   I'm fairly new to svelte and have successfully built components but adapting from your sample where you use a "button" with a class rather than having the Calendar itself have a visual representation is what is baffling me.

I'm sure I can get there by hacking around, but your "Can be compiled to a native web component / custom element" statement, if the procedure was explained is probably the ticket.

Great work though...

**Comment by 6eDesign** [comment]
Hey @tonysoft - thanks for submitting this issue.  Could you provide some additional detail about what you're trying to accomplish?  Generally you would only compile a svelte component to a native web component, or a vanilla-JS "widget", if you were trying to use it outside of a svelte project - but it doesn't sound like that's quite what you're looking for as you've mentioned you're using a "stock svelte dev env."

Are you maybe trying to accomplish this from the demo page? 
```html
<Datepicker format=#{l}, #{F} #{j}, #{Y} bind:formattedSelected bind:dateChosen>
  <button class='custom-button'>
    {#if dateChosen} Chosen: {formattedSelected} {:else} Pick a date {/if}
  </button>
</Datepicker>
```

If so, you could follow this REPL example: https://svelte.dev/repl/387bf3cb2f5a450faa59a49f01741efb?version=3.18.2

You may be right that this could be documented better, if so.  If not, please provide some additional details on your use case.

**Comment by 6eDesign** [comment]
Closing due to lack of clarification.
