### ISSUE TITLE
Is it possible to change the background color?

### ISSUE THREAD

**Issue by ejoflo** [6eDesign/svelte-calendar#76]
I see the theming options that are provided for this component, however I didn't notice any way to change the background color. Is this possible?

**Comment by 6eDesign** [comment]
It doesn't appear possible now, without using global styles.  We can add this capability easily enough, though.

**Comment by 6eDesign** [comment]
V3 of the calendar has been released and includes enhanced theming functionality.   You can design your own theme here in the [theme-editor](https://6edesign.github.io/svelte-calendar/docs/theme-editor/dark) and view examples of custom themes [in these examples](https://6edesign.github.io/svelte-calendar/docs/examples).
