### ISSUE TITLE
Bug: Event handling issues in Popover

### ISSUE THREAD

**Issue by Tharit** [6eDesign/svelte-calendar#79]
The Popover Component seems to have a few issues.

Number 1: when "trigger" is not set it never unregisters the click listener on onmount:
Number 2: The focus loss check does not work if the calendar is used within another component that has a click listener, e.g. the Modal from sveltestrap.
Number 3: In my setup I get warnings "<Popover> received an unexpected slot "default"." 
Number 4: It would be a nice feature if you could handle the "Esc" key to close the popover as well.

**Regarding Number 1:**
Relevant code from Popover.svelte:
```
onMount(() => {
    document.addEventListener('click', checkForFocusLoss);
    if (!trigger) return;
```
=> The onmount callback is never created if "trigger" is not set.

This in turn leads to an exception being thrown if the user clicks somewhere after the calendar has been unmounted.

**Regarding Number 2:**
 Registering the listener with "useCapture=true" and then calling stopPropagation & preventDefault would solve the problem, and make the calendar work within modals.

**Regarding Number 3:**
I'm not really sure where the warnings are coming from when looking at the code.
I'm embedding the DatePicker like this:
```
<DatePicker format={dateFormat} bind:selected={date} bind:formattedSelected={formattedDate}>
    <button class="btn btn-outline-secondary" type="button">Select</button>
 </DatePicker>
```
**Regarding Number 4:**
Similar to the document click handler you could add a keydown handler checking for Esc like this:
```
function handleEscape(evt) {
      if (evt.key && evt.key === 'Escape' && open) {
        evt.stopPropagation();
        evt.preventDefault();
        close();
      }
  }
```

**Comment by 6eDesign** [comment]
Thanks for reporting this issue.  I will take a look when I have some time or review a PR if you have one.

**Comment by avimar** [comment]
I'm also getting this on each load:

`<Popover> received an unexpected slot "default".` in my console

**Comment by 6eDesign** [comment]
I believe all of these issues are fixed in the latest v3 release of the calendar.  Please feel free to check it out and let me know if you're having any problems.
