### ISSUE TITLE
Project is not in a proper state to use with npm

### ISSUE THREAD

**Issue by cotlod** [6eDesign/svelte-calendar#85]
I just tried installing this as a dependency to my project and it will not load as a npm dependency (it might not be wanted to be one from what I understand and just be used as is). But it's kind of unclear how you are to use the package in a project. 

I am. referring to this package [https://www.npmjs.com/package/svelte-calendar](url)

In the current state several modifications are necessary for the project to be used as a dependency:

- es6-object-assign is in the dev dependencies but is used in the main.js file so it should be moved to dependencies
- index.js in the root folder that links exports to main.js' exports
- types (optional, but since svelte provide them, consistency would be good)

I would suggest clarifying the purpose in the readme so that it's clear what need to be done.

**Comment by 6eDesign** [comment]
Hi @cotlod - are you trying to use this dependency outside of a svelte project (for example by typing `require('svelte-calendar')` in a JavaScript file?  Or are you attempting to use this svelte component within another .svelte file?

**Comment by cotlod** [comment]
hey! I'm importing 'svelte-calendar' in a svelte component

**Comment by 6eDesign** [comment]
I'm not sure if we're using different processes but I use svelte-calendar, via NPM, all the time in my svelte projects.  What specific problem are you encountering?

**Comment by cotlod** [comment]
I'm using 

- webpack 4.41
- svelte 3.18
- svelte-loader 2.13
- typescript 3.5

Others libraries are imported normally through standard declaration

eg: `import { writable, Writable } from 'svelte/store'`

.svelte files are not bundled through typescript, it shouldn't change the output. (but I tried defining a typescript module to no avail)

but for `svelte-calendar` since there is no `index.js` in the root folder the automatic import isn't recognizing the module. (from what I gathered). I add the index.js file with a default import for testing and the package got recognized post modification. Hence the issue.

Make sense?

**Comment by 6eDesign** [comment]
You're using typescript inside of your svelte files (I wasn't aware this was possible yet, if so).  The calendar can he imported into a svelte file like other svelte components:

```
<script>
  import Calendar from 'svelte-calendar'
</script>

<Calendar />

```

**Comment by cotlod** [comment]
I'm using typescript for my stores, the .svelte files are handled with svelte-loader+webpack. Indeed typescript supported isnt available yet.

your current exemple throw an error

`index.js Uncaught Error: Cannot find module 'svelte-calendar'
    at webpackMissingModule`

when other libraries are working just fine

**Comment by cotlod** [comment]
I'm using node v13.12.0 and npm v6.14.4 if that can affect anything

**Comment by 6eDesign** [comment]
Are you using svelte-loader with webpack? https://github.com/sveltejs/svelte-loader

The `mainFields` property seems to be used to help webpack find the appropriate svelte file: 

```
resolve: {
    // see below for an explanation
    alias: {
      svelte: path.resolve('node_modules', 'svelte')
    },
    extensions: ['.mjs', '.js', '.svelte'],
    mainFields: ['svelte', 'browser', 'module', 'main']
  },
  module: {
    rules: [
      ...
      {
        test: /\.(html|svelte)$/,
        exclude: /node_modules/,
        use: 'svelte-loader'
      }
      ...
    ]
  }
```
The "svelte" property of package.json is defined for svelte-calendar here: https://github.com/6eDesign/svelte-calendar/blob/master/package.json#L3

**Comment by cotlod** [comment]
yes that's my point, there shoud be an index.js file @ the root of the project so that no configuration to webpack needs to be made. (it's a more standard approach to npm packages)

**Comment by cotlod** [comment]
Like stated previousIy I was able to make it work by adding a index.js @ root of svelte-calendar in my node_modules folder

**Comment by cotlod** [comment]
I think you could also add a main property to your package.json and point to the proper file as moment is doing > https://github.com/moment/moment/blob/1811de9d3e2040cc64882b50eaf9e05b4025b465/package.json#L25

**Comment by rjbks** [comment]
I'm having similar issues. npm install but cannot import into `.svelte` files using something like: `import Calendar from 'svelte-calendar'`. That leads to `Error: Cannot find module 'svelte-calendar'`

**Comment by antony** [comment]
I'm not sure what's going wrong here, but I too have been using `svelte-calendar` for a year or more, in Sapper and in Svelte, without issue. The package is correctly built and working. You don't need an `index.js` file since the `svelte` export from `package.json` points to the correct `.svelte` component file. `main` is not used when building with Svelte.

* Install as a `devDependency`
* import X from 'svelte-calendar`

that's it. fully working.

I used to use it with Webpack but I've since moved to Rollup, however I believe the `svelte-loader` for webpack also respects the `svelte` field in `package.json`.

**Comment by cotlod** [comment]
It works with Webpack if you add the following in your configuration

-  `mainFields: ['svelte', 'browser', 'module', 'main']. `

Which wouldn't be an issue if the package was formatted using an index file. 

I switched to rollup to have typescript support within svelte files and now VSCode is telling me it cant find the module (i'll add a .d.ts file and send a PR) but it's still compiling and working just fine. 

So that's was the point of the thread, not having to change your webpack config to make the lib import like a normal dependency

**Comment by antony** [comment]
In that case, the name of this issue is misleading. It is called "project is not in a proper state to use with npm" when in fact it should be called "my webpack configuration is not properly configured for svelte".

I suppose I don't understand why @6eDesign would need to add an index.js file so that the module will work with your misconfigured webpack project? Seems back to front.

In fact making that change would stop this project working inside a non-svelte project (since it would be trying to import an uncompiled svelte file), which certainly isn't desirable.
