### ISSUE TITLE
Actual full example

### ISSUE THREAD

**Issue by rawoke083** [6eDesign/svelte-calendar#86]
Good comp.. but no-where is there an example as to WHAT to actually import..

**Comment by 6eDesign** [comment]
Hi, this is the same as a svelte file you would import locally.  It is a default export so you can name it whatever you want such as:

```
<script>
import Foobar from 'svelte-calendar'
</script>
<Foobar />
```

**Comment by 6eDesign** [comment]
Updated readme.
