### ISSUE TITLE
Very Frustrating !

### ISSUE THREAD

**Issue by rawoke083** [6eDesign/svelte-calendar#87]
Been looking now through the source code trying to figure out WHAT to ACTUALY import ???
 ` import { Datepicker} from "svelte-calendar"`
The above seems not to work.. Moving on and have to choose another comp !

**Comment by 6eDesign** [comment]
Hi, this is the same as a svelte file you would import locally.  It is a default export so you can name it whatever you want such as:

```
<script>
import Foobar from 'svelte-calendar'
</script>
<Foobar />
```
