### ISSUE TITLE
Block out specific days in the middle of the week

### ISSUE THREAD

**Issue by Full-Stack-Zach** [6eDesign/svelte-calendar#96]
It would be really nice to have a prop similar to the 'start' and 'end' flag currently, but instead of a start and end value, it is an array of days of the week or dates of the month that the calendar will make unavailable (similar to the airbnb calendar).

I need this functionality for something and will work on it myself but if you have any ideas on how to best go about it, I'd love to hear!

**Comment by 6eDesign** [comment]
There is a prop called selectableCallback that you can pass to the calendar.  It is a function that will be called with all dates between start and end.  If it returns true then the day will be selectable, if it returns false it will be blocked/disabled.

**Comment by Full-Stack-Zach** [comment]
Thanks for the reply! I just built another solution and then saw your response haha. I think that your way of doing it is better so I won't push it up. Thank you!
