### ISSUE TITLE
prop end date default value

### ISSUE THREAD

**Issue by miaoz2001** [6eDesign/svelte-calendar#97]
Hi,

I like your work and am using it, but it get me into trouble today....
the default value of end date is set as 2020-09-29 and i didn't change it so my users cannot click any date today....

I understand in your doc, it does say that it should be changed. But i doubt everyone read the doc that carefully and change it...

So i kind of hope that the default value could be something like 2999-12-31 or anything reasonable rather  than 2020-09-29. Or a warning for developer not setting the end date in some way...

BTW, it is the same case in your demo page, date could not be selected....

Thanks!

**Comment by superafroman** [comment]
We were hit by the same problem. If a property should be changed it shouldn't have a default value, so I'd suggest either removing the default or updating it to something dynamic, like `export let end = new Date(new Date().getTime() + (365 * 24 * 60 * 60 * 1000));` and removing the requirement to set it yourself.

**Comment by 6eDesign** [comment]
> We were hit by the same problem. If a property should be changed it shouldn't have a default value, so I'd suggest either removing the default or updating it to something dynamic, like `export let end = new Date(new Date().getTime() + (365 * 24 * 60 * 60 * 1000));` and removing the requirement to set it yourself.

I like the approach of setting it a year out from today.  It should help anybody who's not following the instructions to set a start and end date.  Anyone who's using a start date past that default end date will likely be setting both properties.  

Will push a fix in the next day or so.

**Comment by 6eDesign** [comment]
Fixed in version `2.0.x` - start and end date defaults have been updated to 1 year ago and 1 year in future, respectively.
